// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCriterion(arg1:string,arg2:string,arg3:number):Promise<main.Criterion>;

export function AddOption(arg1:string,arg2:string):Promise<void>;

export function CreateDecision(arg1:string):Promise<main.Decision>;

export function DeleteDecision(arg1:string):Promise<void>;

export function GetDecision(arg1:string):Promise<main.Decision>;

export function GetDecisions():Promise<Array<main.Decision>>;

export function GetResults(arg1:string):Promise<Array<main.OptionResult>>;

export function RemoveCriterion(arg1:string,arg2:string):Promise<void>;

export function RemoveOption(arg1:string,arg2:string):Promise<void>;

export function SetScore(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdateCriterion(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdateDecisionTitle(arg1:string,arg2:string):Promise<void>;
