// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCriterion(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCriterion'](arg1, arg2, arg3);
}

export function AddOption(arg1, arg2) {
  return window['go']['main']['App']['AddOption'](arg1, arg2);
}

export function CreateDecision(arg1) {
  return window['go']['main']['App']['CreateDecision'](arg1);
}

export function DeleteDecision(arg1) {
  return window['go']['main']['App']['DeleteDecision'](arg1);
}

export function GetDecision(arg1) {
  return window['go']['main']['App']['GetDecision'](arg1);
}

export function GetDecisions() {
  return window['go']['main']['App']['GetDecisions']();
}

export function GetResults(arg1) {
  return window['go']['main']['App']['GetResults'](arg1);
}

export function RemoveCriterion(arg1, arg2) {
  return window['go']['main']['App']['RemoveCriterion'](arg1, arg2);
}

export function RemoveOption(arg1, arg2) {
  return window['go']['main']['App']['RemoveOption'](arg1, arg2);
}

export function SetScore(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetScore'](arg1, arg2, arg3, arg4);
}

export function UpdateCriterion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCriterion'](arg1, arg2, arg3, arg4);
}

export function UpdateDecisionTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateDecisionTitle'](arg1, arg2);
}
