// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDecisions(): Promise<Array<{id:string,title:string,created_at:string,options:string[],criteria:Array<{id:string,name:string,weight:number}>,scores:Array<{option:string,criterion_id:string,value:number}>}>>;
export function GetDecision(arg1: string): Promise<{id:string,title:string,created_at:string,options:string[],criteria:Array<{id:string,name:string,weight:number}>,scores:Array<{option:string,criterion_id:string,value:number}>}>;
export function CreateDecision(arg1: string): Promise<{id:string,title:string,created_at:string,options:string[],criteria:Array<{id:string,name:string,weight:number}>,scores:Array<{option:string,criterion_id:string,value:number}>}>;
export function DeleteDecision(arg1: string): Promise<void>;
export function UpdateDecisionTitle(arg1: string, arg2: string): Promise<void>;
export function AddOption(arg1: string, arg2: string): Promise<void>;
export function RemoveOption(arg1: string, arg2: string): Promise<void>;
export function AddCriterion(arg1: string, arg2: string, arg3: number): Promise<{id:string,name:string,weight:number}>;
export function UpdateCriterion(arg1: string, arg2: string, arg3: string, arg4: number): Promise<void>;
export function RemoveCriterion(arg1: string, arg2: string): Promise<void>;
export function SetScore(arg1: string, arg2: string, arg3: string, arg4: number): Promise<void>;
export function GetResults(arg1: string): Promise<Array<{option:string,score:number,rank:number}>>;
